# Generated by Django 4.1.1 on 2022-10-02 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ItemChocolateList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=50)),
                ('item_articleNumber', models.IntegerField()),
                ('item_flavour', models.TextField()),
                ('item_price', models.FloatField()),
                ('item_tan', models.CharField(max_length=5)),
            ],
        ),
    ]
